

export const BUS_EVENTS = {
    UPDATE_PEER_CONNECTION_STATUS: '0',
    UPDATE_REMOTE_USER_MEDIA_STREAM_TRACK: '1',
    UPDATE_REMOTE_USER_MEDIA_TRACK_STATE: '2',

    DATA_CHANEL_OPEN: '3',
    DATA_CHANEL_CLOSE: '4',
    DATA_CHANEL_TEXT_MESSAGE: '5',

    LOCAL_MEDIA_PERMISSIONS_UPDATED: '6'

};


